name: Clone Ingestigator Build Files
on:
  # kick off the job on demand
  workflow_dispatch:
  # and run on a schedule every 12 hours
  schedule:
    - cron: "* */12 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run action
        uses: andrewthetechie/gha-clone-releases@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          src_repo: cadenzabox/ingestigator
