name: Clone Ingestigator Build Files
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run action
        uses: andrewthetechie/gha-clone-releases@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          src_repo: cadenzabox/ingestigator
